#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(5, "hello")
def test_hello():
    r.run_qemu(shell_script([
        'hello',
    ]))
    r.match('^Hello from kernel syscall!', '^I am ICT1012!', '^hello returned 0')

@test(10, "sixfive_test")
def test_sixfive_test():
    r.run_qemu(shell_script([
        'sixfive sixfive.txt',
    ]))
    r.match('^5', '^100', '^18', '^6')

@test(10, "sixfive_readme")
def test_sixfive_readme():
    r.run_qemu(shell_script([
        'sixfive README',
    ]))
    r.match('^6', '^6', '^1810','^6', '^1810')

@test(10, "sixfive_all")
def test_sixfive_all():
    r.run_qemu(shell_script([
        'sixfive sixfive.txt README',
    ]))
    r.match('^5', '^100', '^18', '^6', '^6', '^6', '^1810','^6', '^1810')

@test(10, "xargs")
def test_xargs():
    r.run_qemu(shell_script([
        'sh < xargstest.sh',
        'echo DONE',
    ], 'DONE'))
    matches = re.findall("hello", r.qemu.output)
    assert_equal(len(matches), 3, "Number of appearances of 'hello'")


@test(10, "xargs, multi-line echo")
def test_xargs_multiline1():
    r.run_qemu(shell_script(['(echo 1 ; echo 2) | xargs echo']))
    r.match('^1 2$')
    

@test(10, "xargs, multi-line  -n 1 echo")
def test_xargs_multiline2():
    r.run_qemu(shell_script(['(echo 1 ; echo 2) | xargs -n 1 echo']))
    r.match('^1$', '^2$')

run_tests()
