#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))
  
@test(1, "memdump, format q")
def test_memdump_examples2():
    r.run_qemu(shell_script([ "echo 5465737420313233 | memdump q"]))
    r.match('^Test 123')
    
@test(1, "sixfive_test")
def test_sixfive_test():
    r.run_qemu(shell_script([
        'sixfive sixfive.txt',
    ]))
    r.match('^555', '^56', '^666', '^565')
    
@test(1, "swap32_sys_test_a")
def test_swap32_sys_test_a():
    r.run_qemu(shell_script([
        'swap32_sys 0x12345678',
    ]))
    r.match('^Input:  0x12345678', '^Output: 0x78563412')
    
@test(1, "swap32_sys_test_b")
def test_swap32_sys_test_b():
    r.run_qemu(shell_script([
        'swap32_sys 0xZYXWVUTS',
    ]))
    r.match('^Input:  0xZYXWVUTS', '^Invalid argument')

run_tests()
